### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-website#1]
Add instruction how to generate side.

I got error from cobalt:

```
[nikki]:actix-website$ cobalt --version
Cobalt 0.11.0
[nikki]:actix-website$ cobalt serve
[warn]   No _cobalt.yml file found in current directory, using default config.
[warn]   Syntax theme named 'base16-ocean.dark' ignored. Reason: Themes are unsupported in this build.
[info]   Building from "./actix-website/" into "./actix-website/_site"
Error: serve command failed
Caused by: Failed to parse "more.md"
Caused by: unknown field `extends`, expected one of `permalink`, `slug`, `title`, `description`, `excerpt`, `categories`, `excerpt_separator`, `published_date`, `format`, `layout`, `is_draft`, `data` at line 1 column 1
```

**Comment by krircc** [comment]
@fafhrd91 cool! I think document is important.  It's my wrong. let me explain it. 
```shell
$ git clone https://github.com/actix/actix-website.git
// modify index.liquid or tutorials/community/more markdown file.
// also add or  modify  markdown files in docs/blog DIR.
$ cd actix-website
$ cobalt watch   // it will get 'build' DIR, so only need put files in this 'build' DIR to [actix.github.io](https://github.com/actix/actix.github.io)
```

**Comment by krircc** [comment]
@fafhrd91 the error is because your version 0.11.0. cobalt-rs update today, IT has many Breaking Changes and change the Directory Structure. can you use cobalt-rs 0.10 at the moment. I will update the 
respoitory follow cobalt-rs's version. 
[cobalt-rs v0.10.0](https://github.com/cobalt-org/cobalt.rs/releases/tag/v0.10.0)

**Comment by fafhrd91** [comment]
@krircc could you change color of text (black) to save color as on logo (gray)

**Comment by ami44** [comment]
Can we have look like https://reactjs.org ?

**Comment by fafhrd91** [comment]
I like it!

**Comment by fafhrd91** [comment]
@krircc could you make something similar to reactjs site, in term of color scheme

**Comment by krircc** [comment]
@fafhrd91 @ami44 ok, now I update cobalt v0.11.1

**Comment by ami44** [comment]
You should disable https://actix.github.io/ until it is properly initialized.

**Comment by fafhrd91** [comment]
I like it. Let’s use it, just with grayish colors instead of brownish
@krircc @ami44 would you adapt it?

**Comment by ami44** [comment]
I'm sorry, but I don't have time for a month or two. I follow the progress of the project without further investment.

**Comment by krircc** [comment]
@fafhrd91 @ami44 I think if we want build serious beautiful and Features website, we should use Hugo or Hexo for this.  the demo above 'doc' page is one page, is that enough for contents?  we should have functions , the page's style  is easy to change and make you want.

**Comment by krircc** [comment]
@fafhrd91 @ami44 I make the page more reactjs style.

**Comment by fafhrd91** [comment]
I will add some content
