### ISSUE TITLE
Scoping Routes example code block not matching text

### ISSUE THREAD

**Issue by 06chaynes** [actix/actix-website#111]
on the page: https://actix.rs/docs/url-dispatch/, the example for scoping routes prepares to go over a nested structure using /project/{project_id}/task/{task_id}, but the code block below for the example reflects something different with /users/show/{id}

**Comment by humb1t** [comment]
Hi @06chaynes - did #129 fix the issue?

**Comment by 06chaynes** [comment]
Just saw this reply, it does look to match up now. Good to see continued updates, even small ones. I've really enjoyed building things with this.
