### ISSUE TITLE
Official document should upgrade to match version 2.0.0

### ISSUE THREAD

**Issue by netroby** [actix/actix-website#128]
Official document should upgrade to match version 2.0.0, now it still for actix-web 1.0 series, Need refresh

**Comment by JohnTitor** [comment]
Thanks, I transferred this to actix-website repo, this should be tracked there.

**Comment by simonthum** [comment]
Hi, it's not just "getting started". I tried to compile the hero greeter example right from the front page and that didn't work.

I'm a rust newbie but the examples repo's hello world works fine here so you could improve your newcomer story a lot with mostly copy and paste.

**Comment by DominicWrege** [comment]
Have you added actix-rt to your dependence?
Didn't work it's not a very good description.

**Comment by simonthum** [comment]
Yes, did that. But I need to learn more rust first ;)

**Comment by DominicWrege** [comment]
What have actix-web todo with it?

**Comment by simonthum** [comment]
Hi Dominic, thanks for your efforts! The hero code on the actix page got fixed AFAICT. I think it was missing async fn? Anyway, it now compiles and works like a charm!

**Comment by DominicWrege** [comment]
Ok. Maybe close this issue?!
