### ISSUE TITLE
actix-rt dependencies to use the macro

### ISSUE THREAD

**Issue by ethicnology** [actix/actix-website#133]
Hi everyone, 
i'm upgrading to v2 and i saw the new macro in the updated documentation :
`#[actix_rt::main]`
By adding this i got the following error : 
`failed to resolve: use of undeclared type or module actix_rt `

I think the documentation should mention somewhere that the developer must add actix-rt in his cargo.toml : 
`actix-rt = "1.0.0"`

**Comment by JohnTitor** [comment]
Yeah, it's ideal. I'll update the Installation section at least. But of course, PR is welcome!

**Comment by DominicWrege** [comment]
I wrote it in the getting started section.
[#131](https://github.com/actix/actix-website/pull/131/files#diff-d6cca0653c81db45b2da844166c511c6)
