### ISSUE TITLE
lowercase 'rust' in title

### ISSUE THREAD

**Issue by Maxgy** [actix/actix-website#147]
Is the webpage title and subheading supposed to have a lowercase 'rust'? 

![image](https://user-images.githubusercontent.com/19353212/72959145-73b70c00-3d77-11ea-899d-1c79069a4c34.png)

As of right now, Rust is displayed as lowercase. I understand if this is intentional as to maintain all lowercase letters, but I want to make sure it's not a mistake.

**Comment by JohnTitor** [comment]
Thanks! Should be fixed in #149.
