### ISSUE TITLE
Is it allowed to add a section about a new authorization middleware in the Middlewares page?

### ISSUE THREAD

**Issue by hsluoyz** [actix/actix-website#170]
We have created an authorization middleware for Actix-web based on Casbin: https://github.com/casbin-rs/actix-casbin-auth

Is it OK for us to add a section about it in the official middleware page: https://actix.rs/docs/middleware/ ? If yes, we will make a PR in this repo for you to review.

**Comment by robjtede** [comment]
Its been on my mind to create an "awesome" style repo for promoting these community crates which we could, for example, link to the auth section from the website and would be easier to maintain than adding to directly the website.

**Comment by robjtede** [comment]
the right place for community crates is in the actix-extras readme: https://github.com/actix/actix-extras#community-crates
