### ISSUE TITLE
Clarify the use of actix-rt

### ISSUE THREAD

**Issue by bibhas2** [actix/actix-website#175]
In the [Getting Started](https://actix.rs/docs/getting-started/) page we say:

> If you want to use the ``#[actix_rt::main]`` macro

I am yet to see any alternative to the use of ``#[actix_rt::main]`` macro. If it is there it is not discussed in the guide. It will be easier for the reader if ``actix_rt`` is added as dependency right in the beginning instead of presenting it as a personal choice for the reader.

**Comment by robjtede** [comment]
Now that https://github.com/actix/actix-web/pull/1559 is merged, actix_rt will no longer needed for a hello world server in v3. Docs will be updated acordingly soon.
