### ISSUE TITLE
Database Documentation

### ISSUE THREAD

**Issue by fluffy-samurai** [actix/actix-website#177]
The database documentation on the website seems outdated to the example code.
Website: https://actix.rs/docs/databases/
Example: https://github.com/actix/examples/tree/master/diesel/

Which is considered more accurate as to how one should use diesel and would updated documentation be accepted in this case?

**Comment by robjtede** [comment]
linked to #145

**Comment by fluffy-samurai** [comment]
This appears recently fixed. Thank you!
