### ISSUE TITLE
update CoC contact email

### ISSUE THREAD

**Issue by robjtede** [actix/actix-website#196]

**Comment by JohnTitor** [comment]
(`CODE_OF_CONDUCT.md` on actix, actix-net, and actix-web repos should be updated as well.)

So, we should list your + my email addresses instead?

**Comment by robjtede** [comment]
sure, `robjtede@icloud.com`

could be useful in future to have an email under "@actix.rs"

**Comment by JohnTitor** [comment]
> could be useful in future to have an email under "@actix.rs"

That sounds like a good idea but the domain is owned by Nikolay and it may be burden for them 🤔
