### ISSUE TITLE
A question regarding the sample code

### ISSUE THREAD

**Issue by neilyoung** [actix/actix-website#199]
...provided here:

I'm wondering how this sample is supposed to work. OK, I see the server is started on a separate thread, but if I run this app, the entire server is torn down again immediately, because nobody stops is from doing so.

So what does this sample give?

```
use actix_web::{web, App, HttpResponse, HttpServer, rt::System};
use std::sync::mpsc;
use std::thread;

#[actix_web::main]
async fn main() {
    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let sys = System::new("http-server");

        let srv = HttpServer::new(|| {
            App::new().route("/", web::get().to(|| HttpResponse::Ok()))
        })
        .bind("127.0.0.1:8080")?
        .shutdown_timeout(60) // <- Set shutdown timeout to 60 seconds
        .run();

        let _ = tx.send(srv);
        sys.run()
    });

    let srv = rx.recv().unwrap();

    // pause accepting new connections
    srv.pause().await;
    // resume accepting new connections
    srv.resume().await;
    // stop server
    srv.stop(true).await;
}
```

**Comment by fakeshadow** [comment]
The example shows you that HttpServer would return a handle future when you can run on it. This handle can be sent anywhere you want and using it to pause/resume/stop the server.

**Comment by neilyoung** [comment]
Yepp. Understand that. But this entire sample does not work. If someone would comment that like so, I wouldn't have a problem

**Comment by neilyoung** [comment]
> (Besides await on it and keep the server running)
That's the point

**Comment by robjtede** [comment]
in v4, actix servers can just be `tokio::spawn`ed

or

https://github.com/actix/examples/tree/master/run-in-thread
