### ISSUE TITLE
std::sync::Mutex blocks the thread

### ISSUE THREAD

**Issue by Nonius** [actix/actix-website#201]
https://github.com/actix/actix-website/blob/3a571e036a475bbed3faad53903c8c6309038488/examples/application/src/mutable_state.rs#L3

Instead of `std::sync::Mutex` `tokio::sync::Mutex` should be used otherwise the threads can be blocked and the application comes to a full stop.

**Comment by robjtede** [comment]
The std mutex is fine to use in async code as long as locks aren't held across await points; that's where you run into risk of deadlocks. I'd consider improving the comments/docs around this example but wouldn't want to needlessly turn devs away from the simplest solution.

**Comment by fakeshadow** [comment]
Like robjtede pointed out. Async mutext are more expensive and potential slower when have a short critical session. 
Tokio has pointed out this clearly in it's tutorial: https://tokio.rs/tokio/tutorial/shared-state (Use Tokio's asynchronous mutex)

**Comment by fakeshadow** [comment]
Closing this for now. 
My conclusion is always uses sync mutex when you can. This issue is welcomed to re open or followed discussion if there are reliable soruce pointing otherwise.
