### ISSUE TITLE
Can't compile either static file example

### ISSUE THREAD

**Issue by calaracey** [actix/actix-website#231]
Neither the "Individual File" nor "Directory" example compiles using rust 1.5.3. This is the error that results:

`--> src/main.rs:7:28
  |
7 |         App::new().service(fs::Files::new("/static", ".").show_files_listing())
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpServiceFactory` is not implemented for Files`

Any ideas what I am doing wrong?

**Comment by robjtede** [comment]
can you post what versions of actix-web and actix-files you're using please

**Comment by calaracey** [comment]
I was using actix-files 0.2.1. I switched to 0.5.0 and that solved the problem. Thanks.
