### ISSUE TITLE
HTTP/2 support works with rustls, docs may be outdated

### ISSUE THREAD

**Issue by joepio** [actix/actix-website#235]
The [docs](https://actix.rs/docs/http2/) seem to indicate that HTTP2 is only supported with `openssl`, but my server (running on https://atomicdata.dev) [uses `rustls`](https://github.com/joepio/atomic-data-rust/blob/21fea37c594f238a6f37d7f92bc0e3e6602ec938/server/src/main.rs#L188) and seems to handle HTTP2 just fine ([test here](https://gf.dev/http2-test)).

I think the docs are outdated, and [this file](https://github.com/actix/actix-website/blob/master/content/docs/http2.md) should be updated. Maybe something else is going on, though.

**Comment by jim4067** [comment]
the links to the mentioned RFC's are also broken.
