### ISSUE TITLE
 ^^ the trait `Responder` is not implemented for `NamedFile`

### ISSUE THREAD

**Issue by ArunGust** [actix/actix-website#265]
I got this error after moving form 3.x to 4.x 

 ^^ the trait `Responder` is not implemented for `NamedFile`
    |
    = note: required because of the requirements on the impl of `Responder` for `Result<NamedFile, actix_web::Error>`
note: required by a bound in `Route::to`
   --> C:\RUST\CARGO\registry\src\github.com-1ecc6299db9ec823\actix-web-4.0.1\src\route.rs:186:20
    |
186 |         F::Output: Responder + 'static,
    |                    ^^^^^^^^^ required by this bound in `Route::to`

**Comment by robjtede** [comment]
update your version of actix-files to 0.6
