### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Ofenhed** [actix/actix-website#269]
The documentation holds many broken links (according to [dead link checker](https://www.deadlinkchecker.com/website-dead-link-checker.asp)). I've filtered out false positives.

| Issue | Target URL | Anchor Text | Linked From |
| ---   | ---        | ---         | ---         |
| 404 Not Found | https://actix.rs/docs/extractors/docsrs_match_info | match_info docs | https://actix.rs/docs/extractors/ |
| 404 Not Found | https://actix.rs/docs/extractors/critical_section | critical section | https://actix.rs/docs/extractors/ |
| 404 Not Found | https://actix.rs/docs/extractors/tokio_std_mutex | Tokio&rsquo;s advice on using blocking Mutex in async code | https://actix.rs/docs/extractors/ |
| 404 Not Found | https://docs.rs/actix-web/4.0.1/actix_web/dev/struct.HttpResponseBuilder.html | the force_close() method on HttpResponseBuilder [302 from https://docs.rs/actix-web/4/actix_web/dev/struct.HttpResponseBuilder.html] | https://actix.rs/docs/server/ |
| 404 Not Found | https://docs.rs/actix-web/4.0.1/actix_web/body/enum.ResponseBody.html | ResponseBody [302 from https://docs.rs/actix-web/4/actix_web/body/enum.ResponseBody.html] | https://actix.rs/docs/testing/ |
| 404 Not Found | https://actix.rs/actix-web/actix_web/dev/futures_core::stream::Stream | Stream | https://actix.rs/actix-web/actix_web/dev/enum.Payload.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/web/futures_core::stream::Stream | Stream | https://actix.rs/actix-web/actix_web/web/struct.Payload.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/cookie/all.html | All Items | https://actix.rs/actix-web/actix_web/cookie/index.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix-web/actix_web/struct.HttpResponseBuilder.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/actix_web/trait.ResponseError.js | script/src | https://actix.rs/actix-web/actix_web/trait.ResponseError.html |
| 404 Not Found | https://actix.rs/actix-web/actix_http/h2/futures_core::stream::Stream | Stream | https://actix.rs/actix-web/actix_http/h2/struct.Payload.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/actix_router/resource_path/trait.ResourcePath.js | script/src | https://actix.rs/actix-web/actix_web/dev/trait.ResourcePath.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/time/formatting/formattable/trait.Formattable.js | script/src | https://actix.rs/actix-web/actix_web/cookie/time/formatting/trait.Formattable.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/time/parsing/parsable/trait.Parsable.js | script/src | https://actix.rs/actix-web/actix_web/cookie/time/parsing/trait.Parsable.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/actix_service/transform/trait.Transform.js | script/src | https://actix.rs/actix-web/actix_web/dev/trait.Transform.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/actix_http/body/message_body/trait.MessageBody.js | script/src | https://actix.rs/actix-web/actix_web/body/trait.MessageBody.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/bytes/buf/buf_impl/trait.Buf.js | script/src | https://actix.rs/actix-web/actix_web/web/trait.Buf.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/actix_http/header/into_value/trait.TryIntoHeaderValue.js | script/src | https://actix.rs/actix-web/actix_web/http/header/trait.TryIntoHeaderValue.html |
| -1 Not found: The server name or address could not be resolved  | https://mdn.io/Content-Disposition | a header for a multipart body | https://actix.rs/actix-web/actix_web/http/header/index.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/dev/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix-web/actix_web/dev/struct.Server.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/net/trait@crate::net::ToSocketAddrs | ToSocketAddrs | https://actix.rs/actix-web/actix_web/rt/net/struct.TcpListener.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/net/fn@crate::io::AsyncWriteExt::shutdown | shutdown() | https://actix.rs/actix-web/actix_web/rt/net/struct.UnixStream.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/net/trait@crate::io::AsyncReadExt | AsyncReadExt | https://actix.rs/actix-web/actix_web/rt/net/struct.TcpStream.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/net/trait@crate::io::AsyncWriteExt | AsyncWriteExt | https://actix.rs/actix-web/actix_web/rt/net/struct.TcpStream.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/net/fn@crate::io::AsyncWriteExt::write_all | write_all | https://actix.rs/actix-web/actix_web/rt/net/struct.TcpStream.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/net/fn@crate::io::AsyncReadExt::read | read | https://actix.rs/actix-web/actix_web/rt/net/struct.TcpStream.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/task/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix-web/actix_web/rt/task/struct.JoinHandle.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/macro.select.html | select! | https://actix.rs/actix-web/actix_web/rt/time/struct.Sleep.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/time/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix-web/actix_web/rt/time/struct.Sleep.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/time/timeout_at | timeout_at | https://actix.rs/actix-web/actix_web/rt/time/struct.Timeout.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/web/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix-web/actix_web/web/struct.UrlEncoded.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/time/ext/trait.NumericalDuration.js | script/src | https://actix.rs/actix-web/actix_web/cookie/time/ext/trait.NumericalDuration.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/time/ext/trait.NumericalStdDuration.js | script/src | https://actix.rs/actix-web/actix_web/cookie/time/ext/trait.NumericalStdDuration.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/actix_http/header/as_name/trait.AsHeaderName.js | script/src | https://actix.rs/actix-web/actix_web/http/header/trait.AsHeaderName.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/actix_http/header/into_pair/trait.TryIntoHeaderPair.js | script/src | https://actix.rs/actix-web/actix_web/http/header/trait.TryIntoHeaderPair.html |
| 404 Not Found | https://actix.rs/actix-web/implementors/bytes/buf/buf_mut/trait.BufMut.js | script/src | https://actix.rs/actix-web/actix_web/web/trait.BufMut.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/signal/unix/fn@signal_hook_registry::register | signal_hook::FORBIDDEN | https://actix.rs/actix-web/actix_web/rt/signal/unix/fn.signal.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/task/struct@crate::runtime::Builder | Builder | https://actix.rs/actix-web/actix_web/rt/task/fn.spawn_blocking.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/task/fn@crate::runtime::Runtime::shutdown_timeout | shutdown_timeout | https://actix.rs/actix-web/actix_web/rt/task/fn.spawn_blocking.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/rt/task/macro@crate::select | tokio::select! | https://actix.rs/actix-web/actix_web/rt/task/fn.yield_now.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web/cookie/time/all.html | All Items | https://actix.rs/actix-web/actix_web/cookie/time/index.html |
| 404 Not Found | https://actix.rs/actix-web/actix_http/h1/futures_core::stream::Stream | Stream | https://actix.rs/actix-web/actix_http/h1/struct.Payload.html |
| 404 Not Found | https://actix.rs/actix-web/actix_http/futures_core::stream::Stream | Stream | https://actix.rs/actix-web/actix_http/enum.Payload.html |
| 404 Not Found | https://actix.rs/actix/implementors/actix/trait.Actor.js | script/src | https://actix.rs/actix/actix/trait.Actor.html |
| 404 Not Found | https://actix.rs/actix/implementors/actix/trait.Handler.js | script/src | https://actix.rs/actix/actix/trait.Handler.html |
| 404 Not Found | https://actix.rs/actix/implementors/actix/trait.Message.js | script/src | https://actix.rs/actix/actix/trait.Message.html |
| 404 Not Found | https://actix.rs/actix-web/actix_web_codegen/macro@macro@connect | CONNECT | https://actix.rs/actix-web/actix_web_codegen/index.html |
| 404 Not Found | https://actix.rs/actix-web/actix_http/h2/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix-web/actix_http/h2/struct.Dispatcher.html |
| 404 Not Found | https://actix.rs/actix-web/actix_http/h1/futures_core::Stream | Stream | https://actix.rs/actix-web/actix_http/h1/struct.Codec.html |
| 404 Not Found | https://actix.rs/actix-web/actix_http/h1/futures_sink::Sink | Sink | https://actix.rs/actix-web/actix_http/h1/struct.Codec.html |
| 404 Not Found | https://gitter.im/actix/actix | Community Chat on Gitter | https://actix.rs/actix/actix/index.html |
| 404 Not Found | https://actix.rs/actix/actix/actors/resolver/index.html | resolver | https://actix.rs/actix/actix/index.html |
| 404 Not Found | https://actix.rs/actix/actix/sync/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix/actix/sync/struct.SyncArbiter.html |
| 404 Not Found | https://actix.rs/actix/actix/dev/futures_core::future::TryFuture | TryFuture&lt;Ok = T, Error = ()&gt; | https://actix.rs/actix/actix/dev/struct.ContextFut.html |
| 404 Not Found | https://actix.rs/actix/implementors/futures_core/stream/trait.Stream.js | script/src | https://actix.rs/actix/actix/prelude/trait.Stream.html |
| 404 Not Found | https://actix.rs/actix/implementors/actix/prelude/trait.StreamHandler.js | script/src | https://actix.rs/actix/actix/prelude/trait.StreamHandler.html |

**Comment by KanishkKhurana** [comment]
Hi,
I am a beginner to OpenSource and I feel I can contribute here.
Please let me know if I can contribute here, and how to get started.

**Comment by robjtede** [comment]
This should be looked at again after #266 is deployed.

**Comment by behkod** [comment]
Now that #266 is merged, This is also fine. reminder to close this one.
