### ISSUE TITLE
request monospace font

### ISSUE THREAD

**Issue by erlangparasu** [actix/actix-website#270]
request please use JetBrains Mono as monospace font, thanks :D

**Comment by JohnTitor** [comment]
I think it's just a personal favor rather than a critical issue e.g. a11y, and I don't see a strong motivation here, closing.

**Comment by erlangparasu** [comment]
its like sans serif in firefox. did you see?

**Comment by erlangparasu** [comment]
@JohnTitor 

without 'JetBrains Mono' bold text more look like sans-serif font
![image](https://user-images.githubusercontent.com/20636828/174931320-1018622a-c00f-431c-acde-78c7c65aac3a.png)

with 'JetBrains Mono' bold text look monospaced
![image](https://user-images.githubusercontent.com/20636828/174931066-b9e05f23-4562-466d-be64-9cdc221e8f91.png)
