### ISSUE TITLE
Outdated info in Server section

### ISSUE THREAD

**Issue by Bromles** [actix/actix-website#275]
In [Server](https://actix.rs/docs/server/) in the multithreading section, it states that the default value of workers is equal to the number of logical cores, when in fact it is equal to physical cores

See [issue 957](https://github.com/actix/actix-web/issues/957) in actix-web repository about this migration from logical to physical cores

**Comment by behkod** [comment]
Shouldn't this issue get closed by now?

The docs reflect the correct info right now.
