### ISSUE TITLE
Why is it mostly about actix-web?

### ISSUE THREAD

**Issue by vityafx** [actix/actix-website#28]
I expected the main and the only one official website about `actix` framework to contain great explanation of it, examples, docs, both, about `actix` and `actix-web`, but it is only about `actix-web` it seems. Why is that?

**Comment by fafhrd91** [comment]
All this requires time. Pr is welcome!

**Comment by augustocdias** [comment]
@fafhrd91 I'd like to start working on that. Both to add `actix` docs and also to update the `actix-web` to latest version. 
I don't have that deep knowledge about `actix` and `actix-web` though, so it will be also learning for me about it.
Could you give me a summary of what should be there for which so I can start diving and writing it?

**Comment by leizzer** [comment]
@vityafx from my point of view it is because `actix-web` is what most of the user base is interested in.
And as @fafhrd91 said, creating documentation takes time an effort that doesn't go to other things. Since `actix-web` is pretty complex and it is what most of the people are interested in, applying Paretto's Principle is a must.

@vityafx if you find something missing that you feel like you can collaborate with, please do it :)
you will be supporting your tools

**Comment by vityafx** [comment]
@augustocdias I don't know. I'd like an human-like explanation of things of the `actix actor framework` in the first place, since `actix-web` is another project which uses `actix`. Also, `https://actix.rs` should be splitted into two parts, one for actor framework, one for anything else which was built on top of it. The domain name does not refer to the "web" but it is only about the `actix-web` project and people don't expect that visiting the website.

@leizzer I was not saying that we should remove the `actix-web` website or documentation or anything else. What I was saying is that it is weird that the website about the actor framework does not contain the information about the actor framework, but something else. It's like the website is called "tires" and the website is about cars instead.

Personally, I am interested in `actix`, not `actix-web`. And I can't find this information anywhere else in a simple form.

**Comment by leizzer** [comment]
@vityafx there is the book https://actix.rs/book/actix/ that isn't mentioned much anywhere, it's a WIP but maybe it can help you a bit more

**Comment by JohnTitor** [comment]
I'm going to close this as we now have https://actix.rs/book/actix/.
