### ISSUE TITLE
invalid link to match_info in docs

### ISSUE THREAD

**Issue by amab8901** [actix/actix-website#289]
Actual behavior:
On this page (https://actix.rs/docs/extractors/), there is a link called `(see [match_info docs](https://actix.rs/docs/extractors/docsrs_match_info))`. This link is broken.

Expected behavior:
The link should not be broken.

**Comment by robjtede** [comment]
is it broken on the new site: <https://actix-website.netlify.app> ?

**Comment by amab8901** [comment]
> Is it broken on the new beta site: https://actix-website.netlify.app ?

nope
