### ISSUE TITLE
Actix book link broken

### ISSUE THREAD

**Issue by RemixJazzCode** [actix/actix-website#296]
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Rust Version (I.e, output of `rustc -V`):
- Actix Web Version:

I'm new to actix. when I just looking around actix website, I found actix book hyper link has broken.

actix book link at https://actix.rs/docs/ 

Check it plz.

**Comment by JohnTitor** [comment]
I guess that docusaurus handles all the requests under actix.rs. Maybe it's a good time to migrate the book repo here.
