### ISSUE TITLE
Review and Partially Revert Chinese Changes to Layouts

### ISSUE THREAD

**Issue by mitsuhiko** [actix/actix-website#30]
@krircc the latest changes you made to the templates make this a mess to maintain and it broke things more than once. I do not want to change too much now but before you do any more changes can we discuss why things are done the way they are?

1. why do we need to use different `baseURL`s in the config? This makes multilingual testing really complicated. It spawns multiple hugo servers
2. why do we need to have chinese stuff in the index layout template? Can we not instead have includes that are language specific?
3. Do we need this language specific javascript code? It again makes stuff very messy to maintain and it will get even harder if someone wants to add another language

**Comment by mitsuhiko** [comment]
I tried to clean this up a bit now. It should be significantly more aligned now.

**Comment by krircc** [comment]
@mitsuhiko thanks ！ I know the change  let maintain hard, there some reason.
1:  begin you made the baseURL no work well at 'cn' site, only work in home page, other pages will return 'en' site. 
2: the site write the 'en' content in html not use hugo template like the now you PRS, I can't add 'cn' content well no broken the site
3: the main problem is that I don't know well hugo, only know some syntax these days, so I do it in JS way.

there is another idea: 'cn' site want to add 'blog' nav, there will blogs publish. if 'en' site no need it, it can be 'hidden' at nav. can we add blog? there will be actix 'cn' community, blogs and articles will be there for 'cn' community to learn and biger.

**Comment by krircc** [comment]
@mitsuhiko I will add 'blog' nav, ok?, any language can reuse it or not,  only need chage the html element's 
 css attribute.

**Comment by fafhrd91** [comment]
I suggest fully separate layout for en and cn. cn should use separate set of css, then @krircc could change it without affecting en site. Same for nav, I don’t want to see empty blog section in en

**Comment by krircc** [comment]
ok

**Comment by fafhrd91** [comment]
I don’t think we need blog

**Comment by mitsuhiko** [comment]
I would propose will the blog then.

**Comment by krircc** [comment]
ok, I think cn site shouln't be here, cn site will have more content. I wiil move the content to [actix-cn](https://github.com/actix-cn/actix-cn-website) let your work more easier. only need kept the link in page's nav.
