### ISSUE TITLE
Chunked body request example does not render on website

### ISSUE THREAD

**Issue by coriolinus** [actix/actix-website#308]
https://github.com/actix/actix-website/blob/f3cefa97233e24d7238708b13a2e845d0b3c3d49/docs/request.md?plain=1#L77-L79

![rendered](https://user-images.githubusercontent.com/7822926/216095302-d60f6800-026f-4926-8032-9dcd0dfda1f3.png)

**Comment by behkod** [comment]
Not only that particular example, but none of the other examples were rendering.

Just inserted the missing line & [requested a pull](https://github.com/actix/actix-website/pull/309).
