### ISSUE TITLE
The `connection_type` method should not be called on `HttpResponseBuilder` instance.

### ISSUE THREAD

**Issue by zhongdongy** [actix/actix-website#312]
This [line of code](https://github.com/actix/actix-website/blob/00880c408764f3463238f19aa24f0e1961096c7e/examples/server/src/keep_alive_tp.rs#L6) referenced by official doc [Server | Actix](https://actix.rs/docs/server#keep-alive) is calling `connection_type` method on instance returned by `HttpResponse::Ok()`, and the comment indicates it should close the connection once finished. But this method doesn't exist on [`struct HttpResponseBuilder`](https://docs.rs/actix-web/4.3.0/actix_web/struct.HttpResponseBuilder.html) instance. 

The correct way should be getting a mutable `HttpResponse` instance first, then manipulate its `Connection` HTTP header using `set_connection_type(http:ConnectionType::Close)` from [`struct ResponseHead`](https://docs.rs/actix-web/4.3.0/actix_web/dev/struct.ResponseHead.html#method.set_connection_type). Like this:

```rust
#[get("/")]
async fn index() -> HttpResponse {
    let mut resp = HttpResponse::Ok().finish();
    resp.head_mut().set_connection_type(http::ConnectionType::Close);
    
    resp
}
```

Please correct me if I'm wrong. :pray: :rose:

**Comment by robjtede** [comment]
This is easy enough to fix. My real concern is that this repo's CI did not catch it.
