### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by robjtede** [actix/actix-website#315]
### Discussed in https://github.com/actix/actix-web/discussions/2988

<div type='discussions-op-text'>

<sup>Originally posted by **samiy803** March  3, 2023</sup>
The documentation on the Actix website is great, but I think it's missing a search feature. This would make it a lot easier to navigate between pages and find the information you're looking for.</div>

**Comment by JohnTitor** [comment]
Looking at https://docusaurus.io/docs/search, we have some options:
1. Using Algolia DocSearch
	According to the above docs:
	> The service is free for any open-source project: just make sure to read the [checklist](https://docsearch.algolia.com/docs/who-can-apply/) and [apply to the DocSearch program](https://docsearch.algolia.com/apply).

	That sounds nice, but it feels like too much for our case (I guess it's anything harmful though).
2. Using Local Search
	AFAIK this is the smallest option. We have to find a good plugin but it doesn't add any more external services.
