### ISSUE TITLE
Add "- Actix" to the end of all page titles

### ISSUE THREAD

**Issue by ssokolow** [actix/actix-website#36]
Currently, I have the Actix website's landing page open in a tab in my Tree Style Tab sidebar as the root of a tree of tabs I use as a "TODO: Try rewriting one of my small web projects in Rust using Actix"... but it makes for a very unhelpful tab title, because it just says "Welcome" and I have a lot of tabs.

It's good practice to include the site/project title in each page title, so it would be "Welcome - Actix" in that case.

**Comment by fafhrd91** [comment]
Fixed by #51
