### ISSUE TITLE
Fix organization logo

### ISSUE THREAD

**Issue by hichemfantar** [actix/actix-website#385]
The actix GH organization logo isn't clear in dark mode because It's transparent.

![image](https://github.com/actix/actix-website/assets/34947993/8ff9b89c-f0b7-4d49-9812-2c950859ed7e)

Should be replaced by a white logo with a black background

**Comment by hichemfantar** [comment]
One single image for both.

Black background and the logo in white should work in all circumstances

**Comment by robjtede** [comment]
it's been replaced, thanks for the push to sort this finally

**Comment by hichemfantar** [comment]
You’re welcome! New icon looks nice 🚀✨
