### ISSUE TITLE
Doc bug - missing example code for middleware

### ISSUE THREAD

**Issue by lukepuplett** [actix/actix-website#456]
A bug in the documentation here:

https://actix.rs/docs/middleware

The sample code for creating middleware is empty. I'm still very much learning so I can't submit an update to the docs myself.

**Comment by robjtede** [comment]
seems okay to me:

![2024-09-11_11 27 09-f1eb235d](https://github.com/user-attachments/assets/e81e1137-b993-478e-bd66-80df4a2539a5)

**Comment by lukepuplett** [comment]
Errr... so, I'm on almost latest Chrome, on macOS, but tbh there's no HTML in that code block.

Go to https://actix.rs/docs/middleware and look at the very first code sample:

![image](https://github.com/user-attachments/assets/1bf146a9-868c-415e-b536-a7f4d5e1656f)

Missing HTML:

![image](https://github.com/user-attachments/assets/ea7e6832-1322-420a-8be8-a0209a56b862)

**Comment by robjtede** [comment]
Still can't repreoduce, even on Chrome. Possible your ad block is wrongly catching the code syntax highlighter JS script? Would explain why it's not loading any content into that HTML block.

**Comment by lukepuplett** [comment]
Wow. It's good on my Safari and my phone Chrome, and actually fine in Incognito mode. I don't have an ad blocker. Okay, cool, I'll figure it out.

**Comment by lukepuplett** [comment]
Alright, well since loading it in Incognito and Safari it now loads okay. Interesting. I'll look out for similar issues on Docusaurus pages elsewhere and I'll hit them up if weirdness. Thanks, see ya.
