### ISSUE TITLE
Host link on website is dead

### ISSUE THREAD

**Issue by alekspickle** [actix/actix-website#72]
Found [dead link to Host Predicate](https://actix.rs/docs/actix_web/pred/fn.Host.html) and did not found issue for that. 
Thought you may want to fix it.

**Comment by alexgnatrow** [comment]
I found it [here](https://actix.rs/docs/application/)

**Comment by alexgnatrow** [comment]
I found it [here](https://actix.rs/docs/application/)
<details>
<summary> screenshot</summary>
![screenshot from 2019-02-06 23-55-09](https://user-images.githubusercontent.com/22867443/52376468-ddf17680-2a6a-11e9-99d3-5ea32ab866f2.png)

</details>

**Comment by vi** [comment]
Another broken link: https://actix.rs/actix-web/actix_web/pred/index.html#functions   from page https://actix.rs/docs/application/

**Comment by vi** [comment]
Is https://actix.rs/docs/ about actix-web 0.7 or about that "completely redesigned architecture" 1.0-alpha?

**Comment by cldershem** [comment]
This has been fixed with 9fcd8c1.
