### ISSUE TITLE
Predicate link on website is dead

### ISSUE THREAD

**Issue by mandreyel** [actix/actix-website#73]
[This](https://actix.rs/docs/actix_web/pred/trait.Predicate.html) link to the `Predicate` trait is dead. It's towards the bottom of [this](https://actix.rs/docs/application/) page.

**Comment by DoumanAsh** [comment]
It is dead, because we're transitioning to new version.
The link points to developement documentation which is switched after we merged `1.0` to master branch

**Comment by mandreyel** [comment]
I see, thanks!

**Comment by DoumanAsh** [comment]
Yeah, sorry for inconvenience, for now refer to docs.rs
